title: "Sameer Sayed - Data Science Portfolio"
description: "Aspiring Data Science and Data Analyst portfolio by Sameer Sayed"
baseurl: "/e-portfolio"        # Repository name goes here, with a leading slash
url: "https://sameer-at-git.github.io"   # Domain without trailing slash